//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KücükPrensEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventories
    {
        public int InventoryId { get; set; }
        public Nullable<int> InventoriesTypeId { get; set; }
        public string InventoryBarkod { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> PersonnelId { get; set; }
    
        public virtual InventoriesTypes InventoriesTypes { get; set; }
        public virtual Personnels Personnels { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
