//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KücükPrensEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DemirbasDbEntities1 : DbContext
    {
        public DemirbasDbEntities1()
            : base("name=DemirbasDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Inventories> Inventories { get; set; }
        public virtual DbSet<InventoriesTypes> InventoriesTypes { get; set; }
        public virtual DbSet<Personnels> Personnels { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<PersonnelWithBranches_Result> PersonnelWithBranches()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PersonnelWithBranches_Result>("PersonnelWithBranches");
        }
    
        public virtual ObjectResult<SP_GetDocuments_Result> SP_GetDocuments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDocuments_Result>("SP_GetDocuments");
        }
    
        public virtual ObjectResult<SP_GetInventroies_Result> SP_GetInventroies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetInventroies_Result>("SP_GetInventroies");
        }
    
        public virtual ObjectResult<SP_PersonnelsWithBranch_Result> SP_PersonnelsWithBranch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PersonnelsWithBranch_Result>("SP_PersonnelsWithBranch");
        }
    
        public virtual ObjectResult<SP_GetDocument_Result> SP_GetDocument()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDocument_Result>("SP_GetDocument");
        }
    }
}
